allow-shorthand: false

inherits:
  - strictness_veryhigh

pylint:
  disable:
    - line-too-long  # already checked by pep8/pycodestyle

pep8:
  options:
    max-line-length: 120

pep257:
  disable:
    - D203
    - D212
  enable:
    - D213
