# Run `brew bundle` to install these

# Brews
brew 'vcsh'
brew 'vim'
brew 'pyenv'
brew 'rbenv'
brew 'ruby-build'
brew 'tig'
brew 'ack'
brew 'ag'
brew 'cmake'
brew 'opam'
brew 'nvm'
brew 'tmux'
brew 'reattach-to-user-namespace'
brew 'tree'
brew 'xcproj'
brew 'xctool'
brew 'clang-format'
brew 'fasd'
brew 'hub'
brew 'vcprompt'
brew 'shellcheck'
brew 'checkbashisms'
# brew 'ghi'
# brew 'mobile-shell'
# brew 'gist'
brew 'urlview'
brew 'cppcheck'
brew 'llvm', args: ['with-clang', 'with-lld', 'with-lldb', 'with-rtti', 'with-all-targets', 'with-python']
brew 'splint'
brew 'docker'
brew 'boot2docker'

tap 'thoughtbot/formulae'
brew 'liftoff'

# Casks
brew 'caskroom/cask/brew-cask'
cask 'dropbox'
cask 'bittorrent-sync'
cask 'google-drive'
cask 'iterm2'
cask 'vagrant'
cask 'dash'
cask 'battle-net'
cask 'steam'
# TODO: Postgres.app has an internal check that its real directory is
#       /Applications/Postgres.app/, so even an --appdir=/Applications symlink
#       won't work for it. Would like to eventually fix this.
# cask 'postgres'
cask 'vmware-fusion'
cask 'virtualbox'
cask 'ynab'
cask 'moom'
cask 'balsamiq-mockups'
cask 'hipchat'
cask 'bartender'
# cask 'flux'
# cask 'alfred'
# cask 'adium'
# cask 'slack'
# cask 'textexpander'
# cask 'caffeine'
# cask 'sequel-pro'
# cask 'the-unarchiver'
# cask 'vlc'
# TODO: Google Chrome from cask doesn't play nice with the 1Password extension?
# cask 'google-chrome'
# cask 'skype'
# cask 'transmission'
# cask 'cloudapp'
# cask 'divvy'
# cask 'rdio'
# cask 'disk-inventory-x
# cask 'github'
# TODO: The cask forumla was removed after the download link was removed from
#       the app's homepage. What's the status of Induction.app?
#       https://github.com/caskroom/homebrew-cask/pull/8772
# cask 'induction'
cask 'loading'
cask 'oclint'
# cask 'kitematic'
