# Run `brew bundle` to install these

# Brews
brew 'vcsh'
brew 'vim', args: ['with-lua'] # TODO: with-luajit instead?
brew 'pyenv'
brew 'rbenv'
brew 'ruby-build'
brew 'tig'
brew 'ack'
brew 'ag'
brew 'cmake'
brew 'opam'
brew 'nvm'
brew 'tmux'
brew 'reattach-to-user-namespace'
brew 'tree'
brew 'xcproj'
brew 'xctool'
brew 'clang-format'
brew 'fasd'
brew 'hub'
brew 'vcprompt'
brew 'shellcheck'
brew 'checkbashisms'
# brew 'ghi'
# brew 'mobile-shell'
# brew 'gist'
brew 'urlview'
brew 'cppcheck'
brew 'llvm', args: ['with-clang', 'with-lld', 'with-lldb', 'with-rtti', 'with-all-targets', 'with-python']
brew 'splint'
brew 'docker'
brew 'boot2docker'
brew 'thefuck'
brew 'ctags'
brew 'valgrind'
brew 'chissel'
brew 'bash-completion'
brew 'cpputest'
brew 'ffmpeg'
brew 'gifsicle'
# $ brew install --with-gpgme --with-sidebar-patch https://gist.githubusercontent.com/Pewpewarrows/b9f545306a00004d8009/raw/7e47a7660491f5dfbae31dc43001cc6eb9aac12b/mutt.rb
# brew 'mutt'
brew 'notmuch'

tap 'homebrew/dupes'
brew 'gdb'

tap 'thoughtbot/formulae'
brew 'liftoff'

tap 'tgray/homebrew-tgbrew'
brew 'contacts2'
brew 'muttqt'

# Casks
brew 'caskroom/cask/brew-cask'
cask 'dropbox'
cask 'bittorrent-sync'
cask 'google-drive'
cask 'iterm2'
cask 'vagrant'
cask 'dash'
cask 'battle-net'
cask 'steam'
# TODO: Postgres.app has an internal check that its real directory is
#       /Applications/Postgres.app/, so even an --appdir=/Applications symlink
#       won't work for it. Would like to eventually fix this.
# cask 'postgres'
cask 'vmware-fusion'
cask 'virtualbox'
cask 'ynab'
# cask 'moom'  # TODO: confirm that slate replaces this completely, then remove
cask 'slate'
cask 'balsamiq-mockups'
cask 'hipchat'
cask 'bartender'
# cask 'flux'
# cask 'alfred'
# cask 'adium'
# cask 'slack'
# cask 'textexpander'
# cask 'caffeine'
# cask 'sequel-pro'
# cask 'the-unarchiver'
cask 'vlc'
# TODO: Google Chrome from cask doesn't play nice with the 1Password extension?
# cask 'google-chrome'
# cask 'skype'
# cask 'transmission'
# cask 'cloudapp'
# cask 'divvy'
cask 'disk-inventory-x'
# cask 'github'
# TODO: The cask forumla was removed after the download link was removed from
#       the app's homepage. What's the status of Induction.app?
#       https://github.com/caskroom/homebrew-cask/pull/8772
# cask 'induction'
cask 'loading'
cask 'oclint'
# cask 'kitematic'
cask 'easysimbl'
cask 'flash'
cask 'spotify'
cask 'appcleaner'
cask 'beardedspice'
cask 'mojibar'
cask 'mactex'
cask 'daisydisk'
cask 'anki'
cask 'tunnelblick'
cask 'licecap'
cask 'gpgtools'
